# Generated by Django 2.1.5 on 2019-02-02 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('number_riders', models.IntegerField()),
                ('earliest_time', models.DateTimeField()),
                ('latest_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('arrival_time', models.DateTimeField()),
                ('number_riders', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('EC', 'Economic'), ('RG', 'Regular'), ('LX', 'Luxury')], default='RG', max_length=2)),
                ('free_text', models.CharField(blank=True, max_length=30, null=True)),
                ('is_share', models.IntegerField()),
                ('state', models.IntegerField()),
                ('num_current_rider', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('vehicle_type', models.CharField(choices=[('EC', 'Economic'), ('RG', 'Regular'), ('LX', 'Luxury')], default='RG', max_length=2)),
                ('license_number', models.CharField(max_length=30)),
                ('num_passengers', models.IntegerField()),
                ('special_info', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='sharer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Driver'),
        ),
    ]
