# Generated by Django 2.1.5 on 2019-02-06 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190202_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='sharers',
            field=models.ManyToManyField(related_name='share_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharetrip',
            name='sharer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mysharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mydriver', to='accounts.Driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myrider', to=settings.AUTH_USER_MODEL),
        ),
    ]
